// Generated by CoffeeScript 1.9.3
(function() {
  var placementBasedOnOrientation, tooltipDistanceFromElement, tooltipTemplate;

  tooltipTemplate = "<div class=\"tooltip in\">\n  <div class=\"tooltip-arrow\"></div>\n  <div class=\"tooltip-inner\"></div>\n</div>";

  tooltipDistanceFromElement = 5;

  placementBasedOnOrientation = function($elem, $tooltip, orientation) {
    var elemPos;
    elemPos = $elem.position();
    switch (orientation) {
      case 'left':
        return {
          top: elemPos.top + $elem[0].offsetHeight / 2 - $tooltip[0].offsetHeight / 2,
          left: elemPos.left - $tooltip[0].offsetWidth - tooltipDistanceFromElement
        };
      case 'right':
        return {
          top: elemPos.top + $elem[0].offsetHeight / 2 - $tooltip[0].offsetHeight / 2,
          left: elemPos.left + $elem[0].offsetWidth + tooltipDistanceFromElement
        };
      case 'top':
        return {
          top: elemPos.top - $tooltip[0].offsetHeight - tooltipDistanceFromElement,
          left: elemPos.left - $tooltip[0].offsetWidth / 2 + $elem[0].offsetWidth / 2
        };
      case 'bottom':
        return {
          top: elemPos.top + $elem[0].offsetHeight + tooltipDistanceFromElement,
          left: elemPos.left - $tooltip[0].offsetWidth / 2 + $elem[0].offsetWidth / 2
        };
    }
  };

  window.stateless = window.stateless || {};

  window.stateless.tooltip = function() {
    $(document).on('mouseenter', '[data-tooltip]', function(e) {
      var $elem, $tooltip, orientation, text;
      $elem = $(this);
      orientation = $elem.data('placement') || 'top';
      $elem.data('title', $elem.attr('title')).attr('title', null);
      text = $(this).data('tooltip');
      $tooltip = $(tooltipTemplate).addClass(orientation);
      $tooltip.find('.tooltip-inner').text(text);
      $elem.after($tooltip);
      return $tooltip.css(placementBasedOnOrientation($elem, $tooltip, orientation));
    });
    return $(document).on('mouseleave', '[data-tooltip]', function(e) {
      var $elem;
      $elem = $(this);
      $elem.attr('title', $elem.data('title')).data('title', null);
      return $('.tooltip').remove();
    });
  };

}).call(this);
